name: CI/CD Pipeline for Sentiment Analysis App

# Триггеры для запуска: push в main или создание pull request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # --- ЗАДАЧА 1: Тестирование и проверка качества кода (CI) ---
  test-and-lint:
    runs-on: ubuntu-latest # На какой машине запускать

    steps:
      - name: 1. Checkout code
        uses: actions/checkout@v3

      - name: 2. Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 3. Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 4. Lint with Ruff (проверка стиля кода)
        run: ruff check .

      - name: 5. Format with Black (проверка форматирования)
        run: black --check .
        
      - name: 6. Run tests with Pytest
        run: pytest

  # --- ЗАДАЧА 2: Сборка и публикация Docker-образа (CD) ---
  # Эта задача зависит от успешного выполнения предыдущей
  # и запускается только при push в main
  build-and-push-docker:
    needs: test-and-lint
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout code
        uses: actions/checkout@v3

      - name: 2. Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Логин из секретов GitHub
          password: ${{ secrets.DOCKERHUB_TOKEN }}    # Пароль/токен из секретов GitHub
      
      - name: 3. Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/myminimlops-project:latest # Имя образа
